=== inf25tig09/inf25tig09/animacao.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="animacao">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="filme" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titulo" type="xs:string"/>
              <xs:element name="estudio" type="xs:string"/>
              <xs:element name="ano" type="xs:integer"/>
              <xs:element name="tecnica" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== inf25tig09/inf25tig09/animacao.xml
<?xml version="1.0" encoding="UTF-8"?>
<animacao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="animacao.xsd">

  <filme>
    <titulo>Branca de Neve e os Sete Anões</titulo>
    <estudio>Walt Disney</estudio>
    <ano>1937</ano>
    <tecnica>2D Tradicional</tecnica>
  </filme>

  <filme>
    <titulo>O Rei Leão</titulo>
    <estudio>Walt Disney</estudio>
    <ano>1994</ano>
    <tecnica>2D Tradicional</tecnica>
  </filme>

  <filme>
    <titulo>Toy Story</titulo>
    <estudio>Pixar</estudio>
    <ano>1995</ano>
    <tecnica>3D Digital</tecnica>
  </filme>

  <filme>
    <titulo>Shrek</titulo>
    <estudio>DreamWorks</estudio>
    <ano>2001</ano>
    <tecnica>3D Digital</tecnica>
  </filme>

  <filme>
    <titulo>A Viagem de Chihiro</titulo>
    <estudio>Studio Ghibli</estudio>
    <ano>2001</ano>
    <tecnica>2D Tradicional</tecnica>
  </filme>

  <filme>
    <titulo>Frozen</titulo>
    <estudio>Walt Disney</estudio>
    <ano>2013</ano>
    <tecnica>3D Digital</tecnica>
  </filme>

</animacao>
